name: Construir DB y crear release

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Construir el paquete DEB
      run: ./build.sh

    - name: Subir el DEB a la acción de Github
      uses: actions/upload-artifact@v3
      with:
        name: iesavellaneda-tools.deb
        path: iesavellaneda-tools.deb

    - name: Crear la release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: iesavellaneda-tools.deb
