name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Construir el paquete DEB
      run: ./build.sh

    - name: Subir el DEB a la acción de Github
      uses: actions/upload-artifact@v3
      with:
          name: iesavellaneda-tools.deb
          path: iesavellaneda-tools.deb

    - name: Crear la release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
          artifacts: "iesavellaneda-tools.deb"
